### ISSUE TITLE
Galaxy A71: Android manifest Error

### ISSUE THREAD

**Issue by MikeDev101** [meower-media-co/Meower-Mobile#10]
![Screenshot_20220106-153953_HTML_Viewer.jpg](https://user-images.githubusercontent.com/12957745/148449883-d6d7cad7-c7d2-4cbf-bd62-8b23b15bea6a.jpg)

Meower Mobile latest

**Comment by MikeDev101** [comment]
Not confirmed what version of Android, possibly 10.x or 11.x

**Comment by tnix100** [comment]
Meower Mobile 0.x has been archived.
