### ISSUE TITLE
MeowerMobile doesn't load posts on MediaTek Android 5.x devices

### ISSUE THREAD

**Issue by JoshAtticus** [meower-media-co/Meower-Mobile#4]
The loading screen for posts just shows non-stop. This issue isn't present on Exynos or Qualcomm Android 5.x devices.

**Comment by tnix100** [comment]
Have another go with Meower 0.4! Download the latest APK from this repository.

**Comment by JoshAtticus** [comment]
Already did, still doesn't work

**Comment by tnix100** [comment]
Meower Mobile 0.x has been archived.
